USE master
GO

CREATE DATABASE Sklep

USE Sklep
GO

DROP TABLE Produkty
GO

--zad 2
CREATE TABLE Produkty (
    ID INT NOT NULL UNIQUE IDENTITY ,
    NAZWA VARCHAR(30) NOT NULL CHECK(LEN(NAZWA) >= 3),
    KATEGORIA VARCHAR(15) CHECK(KATEGORIA IN ('ELEKTRYKA', 'HYDRAULIKA', 'BUDOWA')),
    CENA DECIMAL(6,2) NOT NULL CHECK(CENA >= 1 AND CENA <= 9999.99),
    LICZBASZTUK SMALLINT NOT NULL DEFAULT(0) CHECK(LICZBASZTUK >= 0 AND LICZBASZTUK <= 99)
)

--zad 3
INSERT Produkty (NAZWA, KATEGORIA, CENA, LICZBASZTUK) VALUES
('Gniazdka', 'ELEKTRYKA', 5.50, 58),
('Wkrêty', 'BUDOWA', 10.00, 99),
('Rura 2m', 'HYDRAULIKA', 33.20, 42),
('Bezpieczniki', 'ELEKTRYKA', 40.99, 86),
('Drabina', 'BUDOWA', 200.00, 5),
('Cement', 'BUDOWA', 25.00, 17)


SELECT * FROM Produkty
--zad 4
UPDATE Produkty
SET LICZBASZTUK = LICZBASZTUK - 6
WHERE ID = 3

UPDATE Produkty
SET LICZBASZTUK = LICZBASZTUK - 15
WHERE ID = 4

UPDATE Produkty
SET LICZBASZTUK = LICZBASZTUK - 5
WHERE ID = 5

--zad 5
DELETE FROM Produkty
WHERE LICZBASZTUK = 0

--zad 6
UPDATE Produkty
SET CENA = CENA * 0.85
WHERE KATEGORIA = 'ELEKTRYKA'

--zad 7
SELECT KATEGORIA, SUM(LICZBASZTUK * CENA)
FROM Produkty
GROUP BY KATEGORIA